version: '2'
services:

  eureka:
    ports:
      - "8090:8080"
    image: "netflixoss/eureka:1.3.1"

  redis:
    ports:
      - "7379:6379"
    image: "redis:3.2.6"

  metagrapher:
    ports:
      - "8080:8080"
    image: "metagrapher/metagrapher-ui:latest"
    links:
      - "eureka"
      - "redis"
    environment:
      - eureka.port=8080
      - eureka.host=eureka
      - eureka.contextPath=/eureka
      - spring.redis.host=redis


  web-app-1:
    ports:
      - "8081:8080"
    image: "metagrapher/metagrapher-example:latest"
    links:
      - "eureka"
    environment:
      - eureka.port=8080
      - eureka.host=eureka
      - spring.profiles.active=web-app
      - server.externalPort=8081
      - eureka.contextPath=/eureka

  web-app-2:
    ports:
      - "8082:8080"
    image: "metagrapher/metagrapher-example:latest"
    links:
      - "eureka"
    environment:
      - eureka.port=8080
      - eureka.host=eureka
      - spring.profiles.active=web-app
      - server.externalPort=8082
      - eureka.contextPath=/eureka

  mail-app:
    ports:
      - "8083:8080"
    image: "metagrapher/metagrapher-example:latest"
    links:
      - "eureka"
    environment:
      - eureka.port=8080
      - eureka.host=eureka
      - spring.profiles.active=mail-app
      - server.externalPort=8083
      - eureka.contextPath=/eureka

  order-app:
    ports:
      - "8084:8080"
    image: "metagrapher/metagrapher-example:latest"
    links:
      - "eureka"
    environment:
      - eureka.port=8080
      - eureka.host=eureka
      - spring.profiles.active=order-app
      - server.externalPort=8084
      - eureka.contextPath=/eureka

  customer-app:
    ports:
      - "8085:8080"
    image: "metagrapher/metagrapher-example:latest"
    links:
      - "eureka"
    environment:
      - eureka.port=8080
      - eureka.host=eureka
      - spring.profiles.active=customer-app
      - server.externalPort=8085
      - eureka.contextPath=/eureka


